### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ghost** [MioVisman/punbb#1]
Hello dear Mio!

i can't install punbb. this error message is receiving:

Sorry! The page could not be loaded.

This is probably a temporary error. Just refresh the page and retry. If problem continues, please check back in 5-10 minutes.

Database reported: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank VARCHAR(50) NOT NULL DEFAULT '', min_posts MEDIUMINT(8) UNSIGNED NOT NULL D' at line 3 (Errno: 1064).

Failed query: CREATE TABLE pun_ranks ( id INT(10) UNSIGNED AUTO_INCREMENT NOT NULL, rank VARCHAR(50) NOT NULL DEFAULT '', min_posts MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT 0, PRIMARY KEY (id) ) ENGINE = MyISAM CHARACTER SET utf8

The error occurred on line 351 in /var/www/punbb/include/dblayer/mysqli.php

Thank you!
Regards,
Lacesz

**Comment by MioVisman** [comment]
Hi!
https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-R

> 9.3 Keywords and Reserved Words
> ...
> RANK (R); added in 8.0.2 (reserved)
> ...

Tomorrow I'll think about how to fix it.

**Comment by MioVisman** [comment]
Made changes. Test please.
If the installation succeeds, test the change/add ranks in the admin panel.

**Comment by ghost** [comment]
Everything works perfectly! Thank you very much! :-)
