### ISSUE TITLE
Groups is a reserved keyword in MySQL 8

### ISSUE THREAD

**Issue by edwinm** [MioVisman/punbb#2]
When trying to run the code from this repo, I got the following error:

`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups AS g ON g.g_id=u.group_id LEFT JOIN online AS o ON o.ident='x-my-ip-x' at line 1`

This occurs in the function `set_default_user()`.

It turns out `groups` is a reserved keyword in MySQL 8.

See https://dev.mysql.com/doc/refman/8.0/en/keywords.html

Solution:

1) Rename the table `groups` to something else
2) Maybe it's possible to run MySQL in version 7 compatible mode

**Comment by MioVisman** [comment]
To solve, you just need to specify the prefix of the database tables during installation.

If tables have already been created, then
1. set a prefix in your config.php file, exemle `$db_prefix = 'forum_';`
2. add this prefix to all tables in your database

**Comment by MioVisman** [comment]
https://punbb.informer.com/forums/topic/30741/mysql-error-when-attempting-to-run-dbupdatephp/

**Comment by edwinm** [comment]
Thanks a lot!
